### ISSUE TITLE
Annotation in contracts

### ISSUE THREAD

**Issue by ecemetin** [hammadmobin/W2-Encode-Bootcamp-Project#7]
We need to check https://docs.soliditylang.org/en/v0.8.15/natspec-format.html and review the annotations. I will address specific ones here if I find any.

**Comment by ecemetin** [comment]
We can add optional informative tags at the beginning of each script. For example, for this: 

https://github.com/hammadmobin/W2-Encode-Bootcamp-Project/blob/main/Project/scripts/queryProposals.ts 

we can add; 

/// @title A script to query proposals for Ballot contract
/// @author Hammad Mobin
/// @notice You can use this contract for basic queries
/// @custom: W2 Encode BootCamp project -2- Weekend Project

**Comment by hammadmobin** [comment]
Hi,

Changes have been committed. I add NatSpec in both the contracts.

- CustomBallot.sol
- Token.sol

someone has to do the code review and then merge the branch to the main.

**Comment by hammadmobin** [comment]
Hi,

Changes have been committed. I add the author's name and title in every script.

- castVote.ts
- delegate.ts
- deployToken.ts
- deploy.ts
- mint.ts
- queryProposals.ts
- Query.ts

someone has to do the code review and then merge the branch to the main. Now consider this issue resolved and mark this issue closed.
